// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nphsleawzxzizvjspcvx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5waHNsZWF3enh6aXp2anNwY3Z4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjU2NDI2MjcsImV4cCI6MjA4MTIxODYyN30.1UWVHRyHCUTaNsrZ2iIyXMVgYwo4jVCDdNIuAyPOg-M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
});
