// This file is automatically generated in some environments.
// It has been temporarily stubbed out to avoid runtime Supabase
// initialization errors in the browser preview.
//
// If you later need full Supabase client usage on the frontend,
// this file should be regenerated by Lovable Cloud.

// Minimal Database type placeholder to satisfy imports.
export type Database = unknown;

// Stubbed Supabase client – not connected.
// Import using: import { supabase } from "@/integrations/supabase/client";
// but always null‑check before use.
export const supabase: any = null;
